#exception Handling
print("Program start")
try:
    ans=int("1u")
    #print("try block")
finally:
    print("this block always executed when Exception occur or not")

    
print("Program finish")
